server:
  port: 8080

spring:
  application:
    name: huahuadai-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huahuadai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

aliyun:
  oss:
    bucket: readimage
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accesskey: LTAI3A1G8bH8OdvW
    accessKeySecret: NqE9gsYtBFgPy9om5qROgIsScTSL2s
    imageUrl: http://readimage.oss-cn-hangzhou.aliyuncs.com/
    ossPath: images/