server:
    port: 8080

spring:
  application:
    name: huahuadai-api
  datasource:
    url: jdbc:mysql://rm-uf6nv1426n81u2y4g.mysql.rds.aliyuncs.com:3306/yironghua
    username: read01
    password: 1QAZ2wsx
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: r-uf6b90873f6ebf44.redis.rds.aliyuncs.com
    port: 6379
    password: Naquyong_redis
    timeout: 1000
    database: 0
    pool:
      max-active: 200
      max-idle: 180
      min-idle: 20
      max-wait: 100

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

aliyun:
  oss:
    bucket: naquyong-prod
    endpoint: oss-cn-shanghai.aliyuncs.com
    accesskey: 3YNzKETBTsSkU03p
    accessKeySecret: o1lmr3vP6gLaREY4SuBOwDEksJ0reZ
    imageUrl: https://huahuadai-image.fintechsn.com/
    ossPath: facephoto/