server:
  port: 8080

spring:
  application:
    name: huahuadai-api
  datasource:
    url: jdbc:mysql://cmeizu.cn:3306/huahuadai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 119.23.255.116
    port: 6379
    password: 123456
    timeout: 1000
    database: 0
    pool:
      max-active: 200
      max-idle: 180
      min-idle: 20
      max-wait: 100
#  data:
#    mongodb:
#      uri: mongodb://cmeizu:cmz123456@dds-bp1adaedbb75bd44-pub.mongodb.rds.aliyuncs.com:3717/user

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

